using System.Collections.Generic;

namespace BetiJaiDemo.Models
{
    // Autogenerated with http://json2csharp.com/
    public class Hotspot
    {
        public string Name { get; set; }

        public int Id { get; set; }

        public int ZoneId { get; set; }

        public string Location { get; set; }
    }

    public class HotspotList
    {
        public List<Hotspot> Hotspots { get; set; }
    }
}
