using System.Collections.Generic;

namespace BetiJaiDemo.Models
{
    // Autogenerated with http://json2csharp.com/
    public class Zone
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Location { get; set; }

        public string Rotate { get; set; }
    }

    public class ZoneList
    {
        public List<Zone> Zones { get; set; }
    }
}
